import Link from "next/link";
import { ArticleCard, StoryArt } from "../components/ArticleCard";
import { articles, categoryDescriptions, getArticlesByCategory, getLatestArticles } from "../lib/articles";

const sections = ["Commerce", "Business", "Platforms", "Brands", "People"];
const demoNumbers = [
  ["£72,450", "GMV generated by a creator in one month."], ["1,842", "Products sold during a LIVE shopping campaign."],
  ["4.2M", "Views generated by a creator campaign."], ["£8.70", "Average commission earned per order in an example campaign."],
];
export default function Home() {
  const lead = articles[0];
  return <>
    <section className="intro wrap"><span className="eyebrow">Independent creator economy intelligence</span><h1>The business behind the <em>creator economy.</em></h1><div className="intro-bottom"><p>The Chnnl follows the creators, companies, platforms and money shaping the new media economy.</p><a href="#latest" className="text-link">Explore the latest stories <span>↓</span></a></div></section>
    <section className="lead wrap"><Link className="lead-art" href={`/articles/${lead.slug}`}><StoryArt variant={lead.featuredImage} priority /></Link><article><div className="story-meta"><Link href="/commerce">Commerce</Link><span>Lead story</span></div><h2><Link href={`/articles/${lead.slug}`}>{lead.headline}</Link></h2><p>{lead.excerpt}</p><Link href={`/articles/${lead.slug}`} className="text-link">Read the story →</Link></article></section>
    <section id="latest" className="section wrap"><div className="section-head"><div><span className="eyebrow">Fresh intelligence</span><h2>Latest stories</h2></div><Link href="/latest" className="text-link">View all latest →</Link></div><div className="latest-grid">{getLatestArticles(6).map((a, i) => <ArticleCard key={a.id} article={a} compact={i > 2} />)}</div></section>
    <section className="numbers"><div className="wrap"><div className="numbers-head"><div><span className="eyebrow light">Demo data · not verified statistics</span><h2>The Numbers</h2></div><p>The numbers behind the creator economy. A preview of a future data-led editorial product.</p></div><div className="number-grid">{demoNumbers.map(([number, label], i) => <article key={number}><span>0{i + 1}</span><strong>{number}</strong><p>{label}</p><small>Illustrative example</small></article>)}</div></div></section>
    {sections.map((section, i) => <section className={`channel-section wrap ${i % 2 ? "reverse" : ""}`} key={section}><div className="channel-intro"><span className="index">0{i + 1}</span><span className="eyebrow">Editorial channel</span><h2>{section}</h2><p>{categoryDescriptions[section.toLowerCase()]}</p><Link href={`/${section.toLowerCase()}`} className="text-link">Explore {section.toLowerCase()} →</Link></div><div className="channel-stories">{getArticlesByCategory(section).slice(0, 2).map(a => <ArticleCard key={a.id} article={a} compact />)}</div></section>)}
    <section className="opportunity-callout wrap"><span className="eyebrow light">Participation</span><h2>There is more than one way into the creator economy.</h2><p>Find jobs, programmes, partnerships, affiliate opportunities and events.</p><Link href="/opportunities" className="button inverted">Explore opportunities</Link></section>
  </>;
}
