import {articles as localArticles, categoryDescriptions, type Article} from './articles'
import {ALL_ARTICLES_QUERY, ARTICLE_QUERY, CATEGORIES_QUERY, HOME_QUERY, OPPORTUNITIES_QUERY, SETTINGS_QUERY} from '../sanity/queries'

export type SiteSettings = {publicationName: string; tagline: string; description: string; contactEmail: string; logoUrl?: string; logo?: {alt?: string}; faviconUrl?: string; navigation: {label: string; href: string}[]; linkedinUrl?: string; newsletterEyebrow: string; newsletterHeadline: string; newsletterDescription: string; seoTitle?: string; seoDescription?: string; openGraphImageUrl?: string}
export type HomeContent = {eyebrow: string; headline: string; supportingCopy: string; primaryCtaLabel: string; primaryCtaHref: string; latestHeading: string; numbersHeading: string; numbersDescription: string; demonstrationNumbers: {value: string; description: string; sourceUrl?: string}[]; opportunitiesHeadline: string; opportunitiesCopy: string; featuredArticle?: Article}
export type CategoryInfo = {title: string; slug: string; description: string}
export type Opportunity = {id: string; type: string; title: string; organisation: string; location?: string; url?: string; closingDate?: string}

export const defaultSettings: SiteSettings = {publicationName: 'The Chnnl', tagline: 'The business behind the creator economy.', description: 'The Chnnl covers creators, platforms, social commerce, brands and the businesses being built around online influence.', contactEmail: 'wearethechnnl@gmail.com', logoUrl: '/brand/the-chnnl-banner.jpg', logo: {alt: 'The Chnnl'}, faviconUrl: '/favicon.jpg', navigation: ['Latest','Commerce','Business','Platforms','Brands','People','Opportunities'].map(label => ({label, href: `/${label.toLowerCase()}`})), newsletterEyebrow: 'The briefing', newsletterHeadline: 'Know where the creator economy is going.', newsletterDescription: 'A concise editorial briefing. No invented hype.'}
export const defaultHome: HomeContent = {eyebrow: 'Independent creator economy intelligence', headline: 'The business behind the creator economy.', supportingCopy: 'The Chnnl follows the creators, companies, platforms and money shaping the new media economy.', primaryCtaLabel: 'Explore the latest stories', primaryCtaHref: '#latest', latestHeading: 'Latest stories', numbersHeading: 'The Numbers', numbersDescription: 'The numbers behind the creator economy. A preview of a future data-led editorial product.', demonstrationNumbers: [['£72,450','GMV generated by a creator in one month.'],['1,842','Products sold during a LIVE shopping campaign.'],['4.2M','Views generated by a creator campaign.'],['£8.70','Average commission earned per order in an example campaign.']].map(([value,description]) => ({value,description})), opportunitiesHeadline: 'There is more than one way into the creator economy.', opportunitiesCopy: 'Find jobs, programmes, partnerships, affiliate opportunities and events.', featuredArticle: localArticles[0]}

function normalizeArticle(article: Article): Article {
  return {
    id: String(article.id),
    slug: String(article.slug),
    headline: String(article.headline),
    excerpt: String(article.excerpt || article.standfirst || ''),
    standfirst: String(article.standfirst || article.excerpt || ''),
    category: String(article.category || 'Business') as Article['category'],
    author: String(article.author || 'The Chnnl editorial team'),
    publishedAt: String(article.publishedAt),
    featuredImage: String(article.featuredImage || 'signal'),
    featured: Boolean(article.featured),
    tags: Array.isArray(article.tags) ? article.tags.map(String) : [],
    body: Array.isArray(article.body) ? JSON.parse(JSON.stringify(article.body)) : [],
    featuredImageAlt: article.featuredImageAlt ? String(article.featuredImageAlt) : undefined,
  }
}

async function fetchOrFallback<T>(query: string, fallback: T, params: Record<string, unknown> = {}): Promise<T> {
  const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
  const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'
  const sanityEnabled = process.env.NEXT_PUBLIC_SANITY_ENABLED === 'true'
  if (!projectId || !sanityEnabled) return fallback
  try {
    const url = new URL(`https://${projectId}.apicdn.sanity.io/v2026-08-29/data/query/${dataset}`)
    url.searchParams.set('query', query)
    Object.entries(params).forEach(([key, value]) => url.searchParams.set(`$${key}`, JSON.stringify(value)))
    const response = await fetch(url)
    if (!response.ok) return fallback
    const payload = await response.json() as {result?: T}
    return payload.result || fallback
  } catch {
    return fallback
  }
}
export const getSiteSettings = () => fetchOrFallback(SETTINGS_QUERY, defaultSettings)
export const getHomeContent = () => fetchOrFallback(HOME_QUERY, defaultHome)
export async function getAllContentArticles() {
  const fallback = [...localArticles].sort((a,b) => b.publishedAt.localeCompare(a.publishedAt))
  const results = await fetchOrFallback<Article[]>(ALL_ARTICLES_QUERY, fallback)
  return results.map(normalizeArticle)
}
export async function getContentArticle(slug: string) {const fallback = localArticles.find(a => a.slug === slug); const article = await fetchOrFallback<Article | undefined>(ARTICLE_QUERY, fallback, {slug}); return article ? normalizeArticle(article) : undefined}
export async function getContentByCategory(category: string) {const all = await getAllContentArticles(); return category === 'latest' ? all : all.filter(a => a.category.toLowerCase() === category.toLowerCase())}
export async function getContentCategories(): Promise<CategoryInfo[]> {const fallback = Object.entries(categoryDescriptions).filter(([slug]) => slug !== 'latest').map(([slug, description]) => ({slug, title: slug[0].toUpperCase()+slug.slice(1), description})); return fetchOrFallback(CATEGORIES_QUERY, fallback)}
export async function getRelatedContentArticles(article: Article, limit = 3) {const all = await getAllContentArticles(); return all.filter(a => a.id !== article.id && (a.category === article.category || a.tags?.some(t => article.tags?.includes(t)))).slice(0, limit)}
export const getContentOpportunities = () => fetchOrFallback<Opportunity[]>(OPPORTUNITIES_QUERY, [])
